<ul class="main-nav">
	<li>
	<a href="/users"><i class="fa fa-user"></i> Uživatelé</a>
	</li>
	<li>
	<a href="/users"><i class="fa fa-table"></i> Uživatelské role</a>
	</li>
	<!--<li class="collapsible">
		<a href="#" onclick="return false;"><i class="fa fa-list"></i> Form elements</a>
		<ul class="sub-menu">
			<li><a href="form-input.html"><i class="fa fa-pencil"></i>Inputs</a></li>
			<li><a href="form-button.html"><i class="fa fa-tags"></i>Buttons</a></li>
		</ul>
	</li>
	<li><a href="icons.html"><i class="fa fa-star"></i> Buttons &amp; icons</a></li>
	<li><a href="ui.html"><i class="fa fa-arrows-h"></i> Slider elements</a></li>
	<li><a href="grid.html"><i class="fa fa-th"></i> Grid Layout</a></li>
	<li class="collapsible open">
		<a href="#" onclick="return false;"><i class="fa fa-file"></i> Sample pages</i></a>
		<ul class="sub-menu">
			<li><a href="404.html"><i class="fa fa-bug"></i>404</a></li>
			<li><a href="login.html"><i class="fa fa-key"></i>Login</a></li>
		</ul>
	</li>
	<li><a href="charts.html"><i class="fa fa-bar-chart-o"></i> Charts &amp; graphs</a></li>-->
</ul>